name: sarap_finder
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/buko_pandan_shake.jpg
    - assets/images/chicken_inasal_pecho.png
    - assets/images/fire_grill_bbq.png
    - assets/images/google_logo.png
    - assets/images/green_leaf_cafe.png
    - assets/images/inihaw_na_liempo.png
    - assets/images/kanto_refreshments.png
    - assets/images/lolas_eatery.png
    - assets/images/mang-inasal_halohalo.png
    - assets/images/manila_grill.png
    - assets/images/saraplogo.png
    - assets/images/sizzling_pork_sisig.png
    - assets/images/titas_mais_con_hielo.png
    - assets/images/urban_bites.png
    - assets/images/titas_mais_con_hielo.png
    - assets/images/buko_pandan_shake.jpg
    